server:
  port: 8081
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://124.223.50.35:3307/finance
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
logging:
  level:
    root: info
  pattern:
    dateformat: HH:mm:ss
mybatis-plus:
  type-aliases-package: com.funcsales.po
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

