server:
  port: 8120 # 服务端口

spring:
  application:
    name: service-sms # 服务名
    cloud:
      nacos:
        server-addr: localhost:8848 # nacos地址
  datasource:
    url: jdbc:mysql://124.223.50.35:3307/finance?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  #spring:
  redis:
    host: 124.223.50.35
    port: 6379
    database: 0
    password: asdfghjkl #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
logging:
    level:
      com.hdu: debug

#阿里云短信
aliyun:
  sms:
    key-id: LTAI5tHXmHBBDoJTBCYspktm
    key-secret: aeYt27haUSuHxYGGbzHTaEVSvhk4L7
    templateCode: SMS_463600307
    signName: vvc
knife4j:
  enable: true
  openapi:
    title: 基金平台接口文档
    description: "基金平台接口文档"
    concat: vvc
    version: v1.0.0
    group:
      default:
        group-name: 短信服务
        api-rule: package
        api-rule-resources:
          - com.hdu.sms.controller
